version: "3.0"
services:
  laravel-web:
    depends_on:
      - laravel-db
    container_name: laravel-web
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=laravel-db
      - DB_USERNAME=root
      - DB_DATABASE=BankAccount
      - DB_PASSWORD=123456
    ports:
      - "8080:3000"
    networks:
      - laraveldev_net
    restart: always
    volumes:
      - G:\88735059 - Database II\61160100\app:/app
      - G:\88735059 - Database II\61160100\conf\php.ini:/opt/bitnami/php/conf/php.ini:ro

  laravel-db:
    container_name: laravel-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - laraveldev_net
    restart: always
    volumes:
      - G:\88735059 - Database II\61160100\mysql:/var/lib/mysql
      - G:\88735059 - Database II\61160100\data:/root

  laravel-phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=laravel-db
    ports:
      - "8081:80"
    networks:
      - laraveldev_net
    restart: always

networks:
  laraveldev_net:
    driver: bridge
